name: DupePlugin
version: 1.1
main: dev.shigmaqi.dupe.DupePlugin
api-version: 1.21.4
website: https://github.com/SHIGMAQI
commands:
  dupe:
    description: Duplicate held item
    usage: /dupe
